.DEFAULT_GOAL := help

org_code := mahmls

tasks := writeTxt_
tasks := $(foreach t,$(tasks),flow/$t)

sub_tasks := translate_
sub_tasks := $(foreach s, $(foreach t,$(sub_tasks),subFlows/$t), flow/$s)


.PHONY: help install import flow export check readme lint format pre-commit $(tasks) check_env
.PHONY: trans-install translate $(sub_tasks)

help:
	$(info Please use 'make <target>', where <target> is one of)
	$(info )
	$(info   install     install packages and prepare software environment)
	$(info )
	$(info   import      import data required for processing document flow)
	$(info   flow        execute the tasks in the document flow)
	$(info   export      export the data generated by the document flow)
	$(info )
	$(info   readme      generate the readme for the flow/task directories)
	$(info )
	$(info   lint        run the code linters)
	$(info   format      reformat code)
	$(info   pre-commit  run pre-commit checks, runs yaml lint, you need pre-commit)
	$(info )
	$(info Check the makefile to know exactly what each target is doing.)
	@echo # dummy command

install: pyproject.toml
	uv sync --group dev




flow: $(tasks)
$(tasks):
	uv run make -C $@

trans-install: import/models/ai4bharat/IndicTrans2-en/ct2_int8_model
	uv sync --group translate

translate: $(sub_tasks)
$(sub_tasks):
	uv run make -C $@

check:
	uv run op check

readme:
	uv run op readme-mah

lint:
	uv run black -q .
	uv run ruff .

format:
	uv run black -q .
	uv run ruff --fix .

export: readme
	uv run op export-mah


# Use pre-commit if there are lots of edits,
# https://pre-commit.com/ for instructions
# Also set git hook `pre-commit install`
pre-commit:
	pre-commit run --all-files
