description: This folder(task) runs the OCR extracts tables and paragraphs, translates them and writes as a text file.

ignore_docs:

output_dir: 'output'
config_dir: 'conf'
output_stub: 'doc'
read_cache: False


pipeline:
  - name: gcv_recognizer2
    config:
      bucket: opfoundindia
      compress_output: True

  - name: orient_pages
    config:
      min_word_len: 4

  # - name: page_image_builder_embedded
  #   config:
  #     image_dir: /export/page_images

  # - name: html_generator
  #   config:
  #     html_root: output/html
  #     color_dict:
  #       word: blue


  - name: line_finder
    config:
      keep_empty_lines: True
      quick: True
      newline_height_multiple: 1.6

  - name: info_reader

  - name: pdftable_finder
    config:
      skip_row_with_merged_cells: True
      heading_offset: 0 # ignore heading
      header_row: first_table_first_row
      pdfplumber_config:
        vertical_strategy: lines
        horizontal_strategy: lines




