description: This folder(task) runs the OCR extracts tables and paragraphs, translates them and writes as a text file.

ignore_docs: []

output_dir: 'output'
config_dir: 'conf'
output_stub: 'doc'
read_cache: False


pipeline:
  - name: page_image_builder_embedded
    config:
      image_dir: /export/page_images

  - name: skew_detector_wand
    config:
      wand_library: False

  - name: page_rotator
    config:
      skew_cutoff: 0.05

  # - name: gcv_recognizer2
  #   config:
  #     bucket: opfoundindia

  - name: gcv_recognizer
    config:
      bucket: orgpediafoundation
      process_page_image: True
      
  - name: orient_pages
    config:
      min_word_len: 4

  - name: line_finder
    config:
      keep_empty_lines: True
      quick: True
      newline_height_multiple: 1.6
      
