description: This folder(task) runs the OCR extracts tables and paragraphs, translates them and writes as a text file.

ignore_docs: [ ]

output_dir: 'output'
config_dir: 'conf'
output_stub: 'doc'


pipeline:

  - name: gcv_recognizer2
    config:
      bucket: opfi
      compress_output: True


  - name: page_image_builder_embedded
    config:
      image_dir: /export/page_images

  - name: pdftable_finder
    config:
      skip_row_with_merged_cells: False
      heading_offset: 0 # ignore heading
      header_row: never
      pdfplumber_config:
        vertical_strategy: text
        horizontal_strategy: text

  - name: html_generator
    config:
      html_root: output/html
      color_dict:
        table:
          row1: red
          row2: yellow
        table_edges: green
        word: blue
        
